# Generated by Django 4.1.7 on 2023-03-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='feedback',
            new_name='review_text',
        ),
    ]
